version: '2.0'
services:
  nextcloudStablex86:
    #image: ownyourbits/nextcloudpi-armhf
    image: ownyourbits/nextcloudpi-x86
    restart: always
    ports:
      - 4443:4443
      - 443:443
      - 80:80
    volumes:
      - /var/docker_conf/nextcloud/data:/data
networks:
  cloud-network:
    driver: bridge
