---
- name: Bienvenido al instalador de docker y implementacion de contenedores
  hosts: casa
  become: true
  tasks:
  - name: Actualizando repositorios e instalando docker.io y docker-compose...
    apt:
      name: docker.io, docker-compose
      update-cache: yes

  - name: Creando entorno
    file:
      path: nextcloud
      state: directory
  
  - name: Creando entorno 2
    file:
      path: /var/www/nextcloud
      state: directory

  - name: Copiando nextcloud docker-compose...
    copy:
      src: cont1_nextcloud.yml
      dest: nextcloud/docker-compose.yml
      follow: yes

  - name: cd nextcloud
    shell: cd nextcloud

  - name: Creando contenedor...
    docker_compose:
      project_src: nextcloud/

  - name: Porfavor cuando termine de arrancar el contenedor dirijase...
    shell: sleep 5
  - name: sudo nano /var/docker_conf/nextcloud/data/nextcloud/config/config.php
    shell: sleep 5
  - name: y añada en el 'trusted_domains' array... lo siguiente
    shell: sleep 1
  - name: "     2 => '*',"
    shell: sleep 5
